### ISSUE TITLE
End Of Life for the code.

### ISSUE THREAD

**Issue by Just-another-pleb** [erfanjahanshahlo/node-red-contrib-pifacecad#5]
While trying to get things working, I am asking a lot of questions.

It has been pointed out to me that the code use (is written for) python 2.x
Though it is weird that in the install is is including python3.x

Python 2.x has reached its End Of Life.

**Comment by erfanjahanshahlo** [comment]
The library provided by pifacecad is for Python 2 and we can not manually edit it and we do not have the Python version.

**Comment by erfanjahanshahlo** [comment]
It is better to continue the project you are creating without nodered because no project has succeeded with drag and drop, and if it is possible to use a normal character lcd, it would be better and you could use my lcd library. The problem is that I can not access the pifacecad board and try it myself because I am in Iran and this board is not for sale anywhere in Iran.

**Comment by Just-another-pleb** [comment]
Again, no problems.

I was simply advised to let you know.
